# TCL File Generated by Component Editor 12.1sp1
# Fri Feb 19 16:39:42 MST 2016
# DO NOT MODIFY


# 
# dc_motor_driver "dc_motor_driver" v1.0
# null 2016.02.19.16:39:42
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module dc_motor_driver
# 
set_module_property NAME dc_motor_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME dc_motor_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

